suits_db = [
    {
        "title": "Suits",
        "ep_title": "Pilot",
        "season_num": 1,
        "ep_num": 1,
    },
    {
        "title": "Suits",
        "ep_title": "Errors and Omissions",
        "season_num": 1,
        "ep_num": 2,
    },
    {
        "title": "Suits",
        "ep_title": "Inside Track",
        "season_num": 1,
        "ep_num": 3,
    },
    {
        "title": "Suits",
        "ep_title": "Dirty Little Secrets",
        "season_num": 1,
        "ep_num": 4,
    },
    {
        "title": "Suits",
        "ep_title": "Bail Out",
        "season_num": 1,
        "ep_num": 5,
    },
    {
        "title": "Suits",
        "ep_title": "Tricks of the Trade",
        "season_num": 1,
        "ep_num": 6,
    },
    {
        "title": "Suits",
        "ep_title": "Play the Man",
        "season_num": 1,
        "ep_num": 7,
    },
    {
        "title": "Suits",
        "ep_title": "Identity Crisis",
        "season_num": 1,
        "ep_num": 8,
    },
    {
        "title": "Suits",
        "ep_title": "Undefeated",
        "season_num": 1,
        "ep_num": 9,
    },
    {
        "title": "Suits",
        "ep_title": "The Shelf Life",
        "season_num": 1,
        "ep_num": 10,
    },
    {
        "title": "Suits",
        "ep_title": "Rules of the Game",
        "season_num": 1,
        "ep_num": 11,
    },
    {
        "title": "Suits",
        "ep_title": "Dog Fight",
        "season_num": 1,
        "ep_num": 12,
    },
    {
        "title": "Suits",
        "ep_title": "She Knows",
        "season_num": 2,
        "ep_num": 1,
    },
    {
        "title": "Suits",
        "ep_title": "The Choice",
        "season_num": 2,
        "ep_num": 2,
    },
    {
        "title": "Suits",
        "ep_title": "Meet the New Boss",
        "season_num": 2,
        "ep_num": 3,
    },
    {
        "title": "Suits",
        "ep_title": "Discovery",
        "season_num": 2,
        "ep_num": 4,
    },
    {
        "title": "Suits",
        "ep_title": "Break Point",
        "season_num": 2,
        "ep_num": 5,
    },
    {
        "title": "Suits",
        "ep_title": "All In",
        "season_num": 2,
        "ep_num": 6,
    },
    {
        "title": "Suits",
        "ep_title": "Sucker Punch",
        "season_num": 2,
        "ep_num": 7,
    },
    {
        "title": "Suits",
        "ep_title": "Rewind",
        "season_num": 2,
        "ep_num": 8,
    },
    {
        "title": "Suits",
        "ep_title": "Asterisk",
        "season_num": 2,
        "ep_num": 9,
    },
    {
        "title": "Suits",
        "ep_title": "High Noon",
        "season_num": 2,
        "ep_num": 10,
    },
    {
        "title": "Suits",
        "ep_title": "Blind-Sided",
        "season_num": 2,
        "ep_num": 11,
    },
    {
        "title": "Suits",
        "ep_title": "Blood in the Water",
        "season_num": 2,
        "ep_num": 12,
    },
    {
        "title": "Suits",
        "ep_title": "Zane vs. Zane",
        "season_num": 2,
        "ep_num": 13,
    },
    {
        "title": "Suits",
        "ep_title": "He's Back",
        "season_num": 2,
        "ep_num": 14,
    },
    {
        "title": "Suits",
        "ep_title": "Normandy",
        "season_num": 2,
        "ep_num": 15,
    },
    {
        "title": "Suits",
        "ep_title": "War",
        "season_num": 2,
        "ep_num": 16,
    },
    {
        "title": "Suits",
        "ep_title": "The Arrangement",
        "season_num": 3,
        "ep_num": 1,
    },
    {
        "title": "Suits",
        "ep_title": "I Want You to Want Me",
        "season_num": 3,
        "ep_num": 2,
    },
    {
        "title": "Suits",
        "ep_title": "Unfinished Business",
        "season_num": 3,
        "ep_num": 3,
    },
    {
        "title": "Suits",
        "ep_title": "Conflict of Interest",
        "season_num": 3,
        "ep_num": 4,
    },
    {
        "title": "Suits",
        "ep_title": "Shadow of a Doubt",
        "season_num": 3,
        "ep_num": 5,
    },
    {
        "title": "Suits",
        "ep_title": "The Other Time",
        "season_num": 3,
        "ep_num": 6,
    },
    {
        "title": "Suits",
        "ep_title": "She's Mine",
        "season_num": 3,
        "ep_num": 7,
    },
    {
        "title": "Suits",
        "ep_title": "Endgame",
        "season_num": 3,
        "ep_num": 8,
    },
    {
        "title": "Suits",
        "ep_title": "Bad Faith",
        "season_num": 3,
        "ep_num": 9,
    },
    {
        "title": "Suits",
        "ep_title": "Stay",
        "season_num": 3,
        "ep_num": 10,
    },
    {
        "title": "Suits",
        "ep_title": "Buried Secrets",
        "season_num": 3,
        "ep_num": 11,
    },
    {
        "title": "Suits",
        "ep_title": "Yesterday's Gone",
        "season_num": 3,
        "ep_num": 12,
    },
    {
        "title": "Suits",
        "ep_title": "Moot Point",
        "season_num": 3,
        "ep_num": 13,
    },
    {
        "title": "Suits",
        "ep_title": "Heartburn",
        "season_num": 3,
        "ep_num": 14,
    },
    {
        "title": "Suits",
        "ep_title": "Know When to Fold 'Em",
        "season_num": 3,
        "ep_num": 15,
    },
    {
        "title": "Suits",
        "ep_title": "No Way Out",
        "season_num": 3,
        "ep_num": 16,
    },
    {
        "title": "Suits",
        "ep_title": "One-Two-Three Go...",
        "season_num": 4,
        "ep_num": 1,
    },
    {
        "title": "Suits",
        "ep_title": "Breakfast, Lunch and Dinner",
        "season_num": 4,
        "ep_num": 2,
    },
    {
        "title": "Suits",
        "ep_title": "Two in the Knees",
        "season_num": 4,
        "ep_num": 3,
    },
    {
        "title": "Suits",
        "ep_title": "Leveraged",
        "season_num": 4,
        "ep_num": 4,
    },
    {
        "title": "Suits",
        "ep_title": "Pound of Flesh",
        "season_num": 4,
        "ep_num": 5,
    },
    {
        "title": "Suits",
        "ep_title": "Litt the Hell Up",
        "season_num": 4,
        "ep_num": 6,
    },
    {
        "title": "Suits",
        "ep_title": "We're Done",
        "season_num": 4,
        "ep_num": 7,
    },
    {
        "title": "Suits",
        "ep_title": "Exposure",
        "season_num": 4,
        "ep_num": 8,
    },
    {
        "title": "Suits",
        "ep_title": "Gone",
        "season_num": 4,
        "ep_num": 9,
    },
    {
        "title": "Suits",
        "ep_title": "Faith",
        "season_num": 4,
        "ep_num": 10,
    },
    {
        "title": "Suits",
        "ep_title": "Enough Is Enough",
        "season_num": 4,
        "ep_num": 11,
    },
    {
        "title": "Suits",
        "ep_title": "Respect",
        "season_num": 4,
        "ep_num": 12,
    },
    {
        "title": "Suits",
        "ep_title": "Fork in the Road",
        "season_num": 4,
        "ep_num": 13,
    },
    {
        "title": "Suits",
        "ep_title": "Derailed",
        "season_num": 4,
        "ep_num": 14,
    },
    {
        "title": "Suits",
        "ep_title": "Intent",
        "season_num": 4,
        "ep_num": 15,
    },
    {
        "title": "Suits",
        "ep_title": "Not Just a Pretty Face",
        "season_num": 4,
        "ep_num": 16,
    },
    {
        "title": "Suits",
        "ep_title": "Denial",
        "season_num": 5,
        "ep_num": 1,
    },
    {
        "title": "Suits",
        "ep_title": "Compensation",
        "season_num": 5,
        "ep_num": 2,
    },
    {
        "title": "Suits",
        "ep_title": "No Refills",
        "season_num": 5,
        "ep_num": 3,
    },
    {
        "title": "Suits",
        "ep_title": "No Puedo Hacerlo",
        "season_num": 5,
        "ep_num": 4,
    },
    {
        "title": "Suits",
        "ep_title": "Toe to Toe",
        "season_num": 5,
        "ep_num": 5,
    },
    {
        "title": "Suits",
        "ep_title": "Privilege",
        "season_num": 5,
        "ep_num": 6,
    },
    {
        "title": "Suits",
        "ep_title": "Hitting Home",
        "season_num": 5,
        "ep_num": 7,
    },
    {
        "title": "Suits",
        "ep_title": "Mea Culpa",
        "season_num": 5,
        "ep_num": 8,
    },
    {
        "title": "Suits",
        "ep_title": "Uninvited Guests",
        "season_num": 5,
        "ep_num": 9,
    },
    {
        "title": "Suits",
        "ep_title": "Faith",
        "season_num": 5,
        "ep_num": 10,
    },
    {
        "title": "Suits",
        "ep_title": "Blowback",
        "season_num": 5,
        "ep_num": 11,
    },
    {
        "title": "Suits",
        "ep_title": "Live to Fight...",
        "season_num": 5,
        "ep_num": 12,
    },
    {
        "title": "Suits",
        "ep_title": "God's Green Earth",
        "season_num": 5,
        "ep_num": 13,
    },
    {
        "title": "Suits",
        "ep_title": "Self Defense",
        "season_num": 5,
        "ep_num": 14,
    },
    {
        "title": "Suits",
        "ep_title": "Tick Tock",
        "season_num": 5,
        "ep_num": 15,
    },
    {
        "title": "Suits",
        "ep_title": "25th Hour",
        "season_num": 5,
        "ep_num": 16,
    },
    {
        "title": "Suits",
        "ep_title": "To Trouble",
        "season_num": 6,
        "ep_num": 1,
    },
    {
        "title": "Suits",
        "ep_title": "Accounts Payable",
        "season_num": 6,
        "ep_num": 2,
    },
    {
        "title": "Suits",
        "ep_title": "Back on the Map",
        "season_num": 6,
        "ep_num": 3,
    },
    {
        "title": "Suits",
        "ep_title": "Turn",
        "season_num": 6,
        "ep_num": 4,
    },
    {
        "title": "Suits",
        "ep_title": "Trust",
        "season_num": 6,
        "ep_num": 5,
    },
    {
        "title": "Suits",
        "ep_title": "Spain",
        "season_num": 6,
        "ep_num": 6,
    },
    {
        "title": "Suits",
        "ep_title": "Shake the Trees",
        "season_num": 6,
        "ep_num": 7,
    },
    {
        "title": "Suits",
        "ep_title": "Borrowed Time",
        "season_num": 6,
        "ep_num": 8,
    },
    {
        "title": "Suits",
        "ep_title": "The Hand That Feeds You",
        "season_num": 6,
        "ep_num": 9,
    },
    {
        "title": "Suits",
        "ep_title": "P.S.L.",
        "season_num": 6,
        "ep_num": 10,
    },
    {
        "title": "Suits",
        "ep_title": "She's Gone",
        "season_num": 6,
        "ep_num": 11,
    },
    {
        "title": "Suits",
        "ep_title": "The Painting",
        "season_num": 6,
        "ep_num": 12,
    },
    {
        "title": "Suits",
        "ep_title": "Teeth, Nose, Teeth",
        "season_num": 6,
        "ep_num": 13,
    },
    {
        "title": "Suits",
        "ep_title": "Admission of Guilt",
        "season_num": 6,
        "ep_num": 14,
    },
    {
        "title": "Suits",
        "ep_title": "Qid Pro Quo",
        "season_num": 6,
        "ep_num": 15,
    },
    {
        "title": "Suits",
        "ep_title": "Character and Fitness",
        "season_num": 6,
        "ep_num": 16,
    },
    {
        "title": "Suits",
        "ep_title": "Skin in the Game",
        "season_num": 7,
        "ep_num": 1,
    },
    {
        "title": "Suits",
        "ep_title": "The Statue",
        "season_num": 7,
        "ep_num": 2,
    },
    {
        "title": "Suits",
        "ep_title": "Mudmare",
        "season_num": 7,
        "ep_num": 3,
    },
    {
        "title": "Suits",
        "ep_title": "Divide and Conquer",
        "season_num": 7,
        "ep_num": 4,
    },
    {
        "title": "Suits",
        "ep_title": "Brooklyn Housing",
        "season_num": 7,
        "ep_num": 5,
    },
    {
        "title": "Suits",
        "ep_title": "Home to Roost",
        "season_num": 7,
        "ep_num": 6,
    },
    {
        "title": "Suits",
        "ep_title": "Full Disclosure",
        "season_num": 7,
        "ep_num": 7,
    },
    {
        "title": "Suits",
        "ep_title": "100",
        "season_num": 7,
        "ep_num": 8,
    },
    {
        "title": "Suits",
        "ep_title": "Shame",
        "season_num": 7,
        "ep_num": 9,
    },
    {
        "title": "Suits",
        "ep_title": "Donna",
        "season_num": 7,
        "ep_num": 10,
    },
    {
        "title": "Suits",
        "ep_title": "Hard Truths",
        "season_num": 7,
        "ep_num": 11,
    },
    {
        "title": "Suits",
        "ep_title": "Bad Man",
        "season_num": 7,
        "ep_num": 12,
    },
    {
        "title": "Suits",
        "ep_title": "Inevitable",
        "season_num": 7,
        "ep_num": 13,
    },
    {
        "title": "Suits",
        "ep_title": "Pulling the Goalie",
        "season_num": 7,
        "ep_num": 14,
    },
    {
        "title": "Suits",
        "ep_title": "Tiny Violin",
        "season_num": 7,
        "ep_num": 15,
    },
    {
        "title": "Suits",
        "ep_title": "Good-Bye",
        "season_num": 7,
        "ep_num": 16,
    },
    {
        "title": "Suits",
        "ep_title": "Right-Hand Man",
        "season_num": 8,
        "ep_num": 1,
    },
    {
        "title": "Suits",
        "ep_title": "Pecking Order",
        "season_num": 8,
        "ep_num": 2,
    },
    {
        "title": "Suits",
        "ep_title": "Promises, Promises",
        "season_num": 8,
        "ep_num": 3,
    },
    {
        "title": "Suits",
        "ep_title": "Revenue Per Square Foot",
        "season_num": 8,
        "ep_num": 4,
    },
    {
        "title": "Suits",
        "ep_title": "Good Mudding",
        "season_num": 8,
        "ep_num": 5,
    },
    {
        "title": "Suits",
        "ep_title": "Cats, Ballet, Harvey Specter",
        "season_num": 8,
        "ep_num": 6,
    },
    {
        "title": "Suits",
        "ep_title": "Sour Grapes",
        "season_num": 8,
        "ep_num": 7,
    },
    {
        "title": "Suits",
        "ep_title": "Coral Gables",
        "season_num": 8,
        "ep_num": 8,
    },
    {
        "title": "Suits",
        "ep_title": "Motion to Delay",
        "season_num": 8,
        "ep_num": 9,
    },
    {
        "title": "Suits",
        "ep_title": "Managing Partner",
        "season_num": 8,
        "ep_num": 10,
    },
    {
        "title": "Suits",
        "ep_title": "Rocky 8",
        "season_num": 8,
        "ep_num": 11,
    },
    {
        "title": "Suits",
        "ep_title": "Whale Hunt",
        "season_num": 8,
        "ep_num": 12,
    },
    {
        "title": "Suits",
        "ep_title": "The Greater Good",
        "season_num": 8,
        "ep_num": 13,
    },
    {
        "title": "Suits",
        "ep_title": "Peas in a Pod",
        "season_num": 8,
        "ep_num": 14,
    },
    {
        "title": "Suits",
        "ep_title": "Stalking Horse",
        "season_num": 8,
        "ep_num": 15,
    },
    {
        "title": "Suits",
        "ep_title": "Harvey",
        "season_num": 8,
        "ep_num": 16,
    },
    {
        "title": "Suits",
        "ep_title": "Everything's Changed",
        "season_num": 9,
        "ep_num": 1,
    },
    {
        "title": "Suits",
        "ep_title": "Special Master",
        "season_num": 9,
        "ep_num": 2,
    },
    {
        "title": "Suits",
        "ep_title": "Windmills",
        "season_num": 9,
        "ep_num": 3,
    },
    {
        "title": "Suits",
        "ep_title": "Cairo",
        "season_num": 9,
        "ep_num": 4,
    },
    {
        "title": "Suits",
        "ep_title": "If the Shoe Fits",
        "season_num": 9,
        "ep_num": 5,
    },
    {
        "title": "Suits",
        "ep_title": "Whatever It Takes",
        "season_num": 9,
        "ep_num": 6,
    },
    {
        "title": "Suits",
        "ep_title": "Scenic Route",
        "season_num": 9,
        "ep_num": 7,
    },
    {
        "title": "Suits",
        "ep_title": "Prisoner's Dilemma",
        "season_num": 9,
        "ep_num": 8,
    },
    {
        "title": "Suits",
        "ep_title": "Thunder Away",
        "season_num": 9,
        "ep_num": 9,
    },
    {
        "title": "Suits",
        "ep_title": "One Last Con",
        "season_num": 9,
        "ep_num": 10,
    } # Add more episodes here
]

